.PHONY: all clean lint type test test-cov

CMD := {{ cookiecutter.package_manager }} run
PYMODULE := {{ cookiecutter.package_slug }}
EXTRACODE :=

all: mypy-install-types type lint format-check
format: black isort
format-check: black-check isort-check

mypy-install-types:
	$(CMD) mypy --install-types --non-interactive --follow-imports=skip $(PYMODULE)
	

lint:
	$(CMD) flake8 $(PYMODULE) $(EXTRACODE)

type:
	$(CMD) mypy --follow-imports=skip $(PYMODULE) $(EXTRACODE)

isort:
	$(CMD) isort $(PYMODULE) $(EXTRACODE)

isort-check:
	$(CMD) isort --check --verbose $(PYMODULE) $(EXTRACODE)

clean:
	git clean -Xdf # Delete all files in .gitignore

black:
	$(CMD) black .

black-check:
	$(CMD) black --check .

update-libs: # Updates python dependencies and commits
	poetry update
	git add poetry.lock && git commit poetry.lock -m "chore: update project dependencies"
